### ISSUE TITLE
TypeError: get() got an unexpected keyword argument 'language'

### ISSUE THREAD

**Issue by frafra** [geopython/pygeoapi#1061]
I am developing a new plugin, and I found that the `get` method of the class `BaseProvider` should probably accept `language` as parameter:

```
Traceback (most recent call last):
  File "/home/francesco.frassinell/Code/pygeoapi-nina/.venv/lib/python3.8/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/francesco.frassinell/Code/pygeoapi-nina/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/home/francesco.frassinell/Code/pygeoapi-nina/.venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/francesco.frassinell/Code/pygeoapi-nina/.venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/francesco.frassinell/Code/pygeoapi-nina/.venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/francesco.frassinell/Code/pygeoapi-nina/.venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/francesco.frassinell/Code/pygeoapi-nina/.venv/lib/python3.8/site-packages/pygeoapi/flask_app.py", line 216, in collection_items
    api_.get_collection_item(request, collection_id, item_id))
  File "/home/francesco.frassinell/Code/pygeoapi-nina/.venv/lib/python3.8/site-packages/pygeoapi/api.py", line 185, in inner
    headers, status, content = func(*args, **kwargs)
  File "/home/francesco.frassinell/Code/pygeoapi-nina/.venv/lib/python3.8/site-packages/pygeoapi/api.py", line 167, in inner
    return func(cls, req_out, *args[2:])
  File "/home/francesco.frassinell/Code/pygeoapi-nina/.venv/lib/python3.8/site-packages/pygeoapi/api.py", line 2073, in get_collection_item
    content = p.get(identifier, language=prv_locale)
TypeError: get() got an unexpected keyword argument 'language'
```

I have not implemented a custom `get` function in my plugin.

https://github.com/geopython/pygeoapi/blob/20c1f3296634515ef719b20dd1d5d58808058e58/pygeoapi/provider/base.py#L134

pygeoapi version 0.13.0.

**Comment by webb-ben** [comment]
This is handled in other providers by including kwargs in the function definition as seen here https://github.com/geopython/pygeoapi/blob/ddd9c70f93f93a27d1f92142d3494bd50d1c16b4/pygeoapi/provider/elasticsearch_.py#L344
