### ISSUE TITLE
pygeoapi master needs jinja2 < 3.0.0

### ISSUE THREAD

**Issue by TAlonglong** [geopython/pygeoapi#1101]
**Description**
By accident I installed latest jinja2 3.1.2 from conda-forge

**Screenshots/Tracebacks**
```
.1 - - [13/Jan/2023 13:36:30] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/trygveas/miniconda3/envs/pygeoapi/lib/python3.9/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/trygveas/miniconda3/envs/pygeoapi/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/home/trygveas/miniconda3/envs/pygeoapi/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/trygveas/miniconda3/envs/pygeoapi/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/trygveas/miniconda3/envs/pygeoapi/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/trygveas/miniconda3/envs/pygeoapi/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/trygveas/Git/pygeoapi/pygeoapi/flask_app.py", line 127, in landing_page
    return get_response(api_.landing_page(request))
  File "/home/trygveas/Git/pygeoapi/pygeoapi/api.py", line 195, in inner
    headers, status, content = func(*args, **kwargs)
  File "/home/trygveas/Git/pygeoapi/pygeoapi/api.py", line 179, in inner
    return func(cls, req_out)
  File "/home/trygveas/Git/pygeoapi/pygeoapi/linked_data.py", line 59, in inner
    return func(*args, **kwargs)
  File "/home/trygveas/Git/pygeoapi/pygeoapi/api.py", line 750, in landing_page
    content = render_j2_template(self.config, 'landing_page.html', fcm,
  File "/home/trygveas/Git/pygeoapi/pygeoapi/util.py", line 334, in render_j2_template
    env = Environment(loader=FileSystemLoader(templates_path),
  File "/home/trygveas/miniconda3/envs/pygeoapi/lib/python3.9/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/home/trygveas/miniconda3/envs/pygeoapi/lib/python3.9/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/home/trygveas/miniconda3/envs/pygeoapi/lib/python3.9/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'autoescape'
```
**Environment**
 - OS: ubuntu bionic
 - Python version: python 3.9
 - pygeoapi version: master

**Additional context**
I solved this by installing `conda install jinja2=2.11.3 -c conda-forge`

**Comment by david-i-berry** [comment]
Removing the 'jinja2.ext.autoescape' from the line below should fix the error:

https://github.com/geopython/pygeoapi/blob/fcacf69c5b4450ab74a21edeab8c1ff05c92ab42/pygeoapi/util.py#L346

See https://jinja.palletsprojects.com/en/2.9.x/extensions/#autoescape-extension for context.

**Comment by totycro** [comment]
This has been fixed by this commit already and the issue can be closed.
https://github.com/geopython/pygeoapi/commit/997a83530e1c1f614287b20d516ca6f87dd9d2bd
