### ISSUE TITLE
item.html gives error when id-field is not a string

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi#1107]
**Description**
item.html gives error when id-field is not a string

**Steps to Reproduce**
* have any Collection where the id is integer
* browse to Items
* click on single Item
* observe error

For example the "Large Lakes GeoJSON Collection" on demo server:
* https://demo.pygeoapi.io/master/collections/ogr_geojson_lakes/items/0 ("Internal Server Error")
* https://demo.pygeoapi.io/stable/collections/ogr_geojson_lakes/items/0 (works)

**Expected behavior**
Show the Item HTML

**Screenshots/Tracebacks**
The server shows this error trace:

```
[2023-01-18T14:33:17Z] {/usr/lib/python3/dist-packages/flask/app.py:1890} ERROR - Exception on /collections/ogr_geojson_lakes/items/0 [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/pygeoapi/pygeoapi/flask_app.py", line 219, in collection_items
    api_.get_collection_item(request, collection_id, item_id))
  File "/pygeoapi/pygeoapi/api.py", line 195, in inner
    headers, status, content = func(*args, **kwargs)
  File "/pygeoapi/pygeoapi/api.py", line 177, in inner
    return func(cls, req_out, *args[2:])
  File "/pygeoapi/pygeoapi/api.py", line 2216, in get_collection_item
    content = render_j2_template(self.config,
  File "/pygeoapi/pygeoapi/util.py", line 378, in render_j2_template
    return template.render(config=l10n.translate_struct(config, locale_, True),
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/pygeoapi/pygeoapi/templates/collections/items/item.html", line 2, in top-level template code
    {% set ptitle = data['properties'][data['title_field']] or "Item " + data['id'] %}
TypeError: can only concatenate str (not "int") to str
```
The last line is relevant as it causes the error:

`{% set ptitle = data['properties'][data['title_field']] or "Item " + data['id'] %}`
This was introduced on dec 8, 2022 #1064 - rev f9fb2c600551f2ff11b9e2fb2d3b3aff8c243c98.
Earlier versions had:

`{% set ptitle = data['properties'][data['title_field']] or ("Item {}".format(data['id'])) %}`

**Environment**
 - OS: any
 - Python version: any
 - pygeoapi version: later than dec 8, 2022

**Additional context**
Think the fix is simple. Don't know if 'id' attribute is mandatory. Not sure if f-strings will work in Jinja2 templates though.
@tomkralidis

**Comment by tomkralidis** [comment]
@justb4 PR in #1109
