### ISSUE TITLE
"5 minute install" instructions appear to not be working correctly

### ISSUE THREAD

**Issue by isedwards** [geopython/pygeoapi#1270]
**Description**
If I follow the "5 minute install" instructions *exactly* as they are written at pygeoapi.io then `pygeoapi serve` gives the error: `jinja2.exceptions.TemplateNotFound: landing_page.html`

**Steps to Reproduce**
[pygeoapi.io/#install-in-5-minutes](https://pygeoapi.io/#install-in-5-minutes)

**Expected behavior**
`pygeoapi serve` serves initial landing page.

**Screenshots/Tracebacks**
```python
Traceback (most recent call last):
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.16.dev0-py3.9.egg/pygeoapi/flask_app.py", line 132, in landing_page
    return get_response(api_.landing_page(request))
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.16.dev0-py3.9.egg/pygeoapi/api.py", line 210, in inner
    headers, status, content = func(*args, **kwargs)
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.16.dev0-py3.9.egg/pygeoapi/api.py", line 194, in inner
    return func(cls, req_out)
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.16.dev0-py3.9.egg/pygeoapi/linked_data.py", line 60, in inner
    return func(*args, **kwargs)
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.16.dev0-py3.9.egg/pygeoapi/api.py", line 782, in landing_page
    content = render_j2_template(self.tpl_config, 'landing_page.html',
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.16.dev0-py3.9.egg/pygeoapi/util.py", line 437, in render_j2_template
    template = env.get_template(template)
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/isedwards/git/tmp/pygeoapi/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: landing_page.html
```

**Environment**
 - OS: MacOS 13.0 (Intel)
 - Python version: 3.9.6
 - pygeoapi version: latest

**Additional context**
In the 5 minute install instructions, `python3 setup.py install` creates a copy of the package in the venv site-packages directory. Then, when I run `pygeoapi serve` (from the original cloned directory) I get the error which appears to be related to paths.

Usually, I use a slightly modifed method to install pygeoapi using pip's 'editable' (`-e`) option so that the version that I have cloned, and I am editing locally, is also the version that is installed/imported. When pygeoapi is installed in this way there is no problem with the path to templates and the landing page is rendered successfully:

```python
python3 -m venv pygeoapi
cd pygeoapi
. bin/activate
git clone https://github.com/geopython/pygeoapi.git
# -- OLD --
## cd pygeoapi
## pip3 install -r requirements.txt
## python3 setup.py install
# --- NEW --
# Install pygeoapi directory as an editable package
# instead of making a copy in site-packages
pip install -e pygeoapi
cd pygeoapi
# ----------
cp pygeoapi-config.yml example-config.yml
vi example-config.yml  # edit as required
export PYGEOAPI_CONFIG=example-config.yml
export PYGEOAPI_OPENAPI=example-openapi.yml
pygeoapi openapi generate $PYGEOAPI_CONFIG --output-file $PYGEOAPI_OPENAPI
pygeoapi serve
# in another terminal
curl http://localhost:5000  # or open in a web browser

**Comment by tomkralidis** [comment]
@isedwards thanks for the report.  I can't seem to reproduce/works fine here.  Having said this, we could simply replace `python3 setup.py install` with `pip3 install -e .`, so:

```bash
python3 -m venv pygeoapi
cd pygeoapi
. bin/activate
git clone https://github.com/geopython/pygeoapi.git
cd pygeoapi
pip3 install -r requirements.txt
pip3 install -e .
cp pygeoapi-config.yml example-config.yml
vi example-config.yml  # edit as required
export PYGEOAPI_CONFIG=example-config.yml
export PYGEOAPI_OPENAPI=example-openapi.yml
pygeoapi openapi generate $PYGEOAPI_CONFIG --output-file $PYGEOAPI_OPENAPI
pygeoapi serve
# in another terminal
curl http://localhost:5000  # or open in a web browser
```

Does this work for you?

**Comment by isedwards** [comment]
This isn't causing a problem for anyone - let's close.
