### ISSUE TITLE
CQL spatial queries require knowing masked PostgreSQLProvider geometry field 

### ISSUE THREAD

**Issue by webb-ben** [geopython/pygeoapi#1350]
**Description**
Spatial CQL queries to OGC API Features using PostgreSQLProvider produce confusing results. using `geometry` (the only queryable exposed via OGC API - Features) returns a 500 status (traceback below) with no information on why the user is seeing an error code.

**Steps to Reproduce**
Go to:

[INTERSECTS(geometry,%20POINT(42.57%20-116.72))](https://nhdpv2-census.internetofwater.app/collections/2020/items?filter=INTERSECTS(geometry,%20POINT(42.57%20-116.72))&f=json)

The CQL intersection works, you just need to know the provided geom_field which is not exposed via pygeoapi:

[geom_field: shape](https://github.com/internetofwater/nhdpv2-census/blob/main/pygeoapi/census.config.yml#L126)

[INTERSECTS(shape,%20POINT(42.57%20-116.72))](https://nhdpv2-census.internetofwater.app/collections/2020/items?filter=INTERSECTS(shape,%20POINT(42.57%20-116.72))&f=json)

**Expected behavior**
pygeoapi is able to inform CQL queries using the term "geometry" with the corresponding field as specified in "geom_field" or a better handled error that informs the user of the source of the error - and potentially what field they should be using instead. 

**Screenshots/Tracebacks**
- pygeoapi 500 response error traceback
```
"Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/pygeoapi/pygeoapi/flask_app.py", line 205, in collection_items
    api_.get_collection_items(request, collection_id))
  File "/pygeoapi/pygeoapi/api.py", line 214, in inner
    headers, status, content = func(*args, **kwargs)
  File "/pygeoapi/pygeoapi/api.py", line 196, in inner
    return func(cls, req_out, *args[2:])
  File "/pygeoapi/pygeoapi/api.py", line 1653, in get_collection_items
    content = p.query(offset=offset, limit=limit,
  File "/pygeoapi/pygeoapi/provider/postgresql.py", line 161, in query
    cql_filters = self._get_cql_filters(filterq)
  File "/pygeoapi/pygeoapi/provider/postgresql.py", line 438, in _get_cql_filters
    cql_filters = to_filter(filterq, field_mapping)
  File "/usr/local/lib/python3.10/dist-packages/pygeofilter/backends/sqlalchemy/evaluate.py", line 147, in to_filter
    return SQLAlchemyFilterEvaluator(field_mapping).evaluate(ast)
  File "/usr/local/lib/python3.10/dist-packages/pygeofilter/backends/evaluator.py", line 109, in evaluate
    result = handler(self, node, *sub_args)
  File "/usr/local/lib/python3.10/dist-packages/pygeofilter/backends/sqlalchemy/evaluate.py", line 77, in spatial_operation
    return filters.spatial(
  File "/usr/local/lib/python3.10/dist-packages/pygeofilter/backends/sqlalchemy/filters.py", line 239, in spatial
    return _op.function(lhs, rhs)
  File "/usr/local/lib/python3.10/dist-packages/pygeofilter/backends/sqlalchemy/filters.py", line 57, in <lambda>
    "INTERSECTS": lambda f, a: f.ST_Intersects(a),
AttributeError: 'str' object has no attribute 'ST_Intersects'"
```
- Queryables
![image](https://github.com/geopython/pygeoapi/assets/40066515/25015bb0-7e81-428f-af08-749c28e2366e)

**Environment**
 - OS: Linux
 - Python version: 3.7
 - pygeoapi version: 0.16.dev0

**Additional context**

**Comment by tomkralidis** [comment]
ping @KoalaGeo; any idea here?

**Comment by ricardogsilva** [comment]
@KoalaGeo @tomkralidis please check out my pending PR for a proposal of a solution to this issue

**Comment by tomkralidis** [comment]
I think the easiest approach is for pygeoapi always advertise a `geometry` geometry in `.../queryables`, and for the given provider look for a `geom_field` in the provider definition and use as required.

**Comment by ricardogsilva** [comment]
> I think the easiest approach is for pygeoapi always advertise a `geometry` geometry in `.../queryables`, and for the given provider look for a `geom_field` in the provider definition and use as required.
> 

Yes, that is the approach implemented in my PR.

**Comment by KoalaGeo** [comment]
@ricardogsilva good fix. This was on our to do list, in the interim we've been making sure to rename our geometry columns "shape" this then matches the examples in the OGCAPI documentation & examples.
