### ISSUE TITLE
Example section in PROCESS_METADATA is mandatory

### ISSUE THREAD

**Issue by FrancescoIngv** [geopython/pygeoapi#1424]
**Description**
I understand the section `example` is not required in `PROCESS_METADATA`,
but a `processes` request will fail if a processor has not the section `example` in `PROCESS_METADATA`

**Steps to Reproduce**
Remove `example` section in `PROCESS_METADATA` of one the the Processors.
Running the following command:
`curl --verbose  localhost:5000/processes`
returns:
```
*   Trying 127.0.0.1:5000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /processes HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 INTERNAL SERVER ERROR
< Server: Werkzeug/3.0.1 Python/3.8.10
< Date: Tue, 12 Dec 2023 16:53:09 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 265
< Connection: close
< 
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
* Closing connection 0

```

**Expected behavior**
The description of the processes.

**Screenshots/Tracebacks**
[2023-12-12T17:19:50Z] {/home/francesco/Progetti/OGC_API/pyGeoApi_test/.venv/lib/python3.8/site-packages/werkzeug/_internal.py:96} INFO - 127.0.0.1 - - [12/Dec/2023 17:19:50] "GET /processes HTTP/1.1" 500 -
[2023-12-12T17:19:50Z] {/home/francesco/Progetti/OGC_API/pyGeoApi_test/.venv/lib/python3.8/site-packages/werkzeug/_internal.py:96} ERROR - Error on request:
Traceback (most recent call last):
  File "/home/francesco/Progetti/OGC_API/pyGeoApi_test/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/home/francesco/Progetti/OGC_API/pyGeoApi_test/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in execute
    application_iter = app(environ, start_response)
  File "/home/francesco/Progetti/OGC_API/pyGeoApi_test/.venv/lib/python3.8/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/francesco/Progetti/OGC_API/pyGeoApi_test/.venv/lib/python3.8/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
  File "/home/francesco/Progetti/OGC_API/pyGeoApi_test/.venv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/francesco/Progetti/OGC_API/pyGeoApi_test/.venv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/francesco/Progetti/OGC_API/pyGeoApi_test/.venv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/francesco/Progetti/OGC_API/pyGeoApi_test/.venv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/francesco/Progetti/OGC_API/pyGeoApi_test/pygeoapi/pygeoapi/flask_app.py", line 354, in get_processes
    return get_response(api_.describe_processes(request, process_id))
  File "/home/francesco/Progetti/OGC_API/pyGeoApi_test/pygeoapi/pygeoapi/api.py", line 221, in inner
    headers, status, content = func(*args, **kwargs)
  File "/home/francesco/Progetti/OGC_API/pyGeoApi_test/pygeoapi/pygeoapi/api.py", line 203, in inner
    return func(cls, req_out, *args[2:])
  File "/home/francesco/Progetti/OGC_API/pyGeoApi_test/pygeoapi/pygeoapi/linked_data.py", line 60, in inner
    return func(*args, **kwargs)
  File "/home/francesco/Progetti/OGC_API/pyGeoApi_test/pygeoapi/pygeoapi/api.py", line 3317, in describe_processes
    p2.pop('example')
KeyError: 'example'

**Environment**
 - OS: ubuntu
 - Python version: 3.8
 - pygeoapi version: latest

**Additional context**
Can be solved changing line 3317 of api.py:
from
`                    p2.pop('example')
`to
`                    p2.pop('example', None)
`
By the way also 'inputs' should become optional, may be appropriate to add the default also at line 3315 of api.py

**Comment by totycro** [comment]
The pull request linked above should address this.
