### ISSUE TITLE
ModuleNotFoundError: No module named 'elasticsearch'

### ISSUE THREAD

**Issue by PeaceNlove** [geopython/pygeoapi#172]
Hello,

I'm trying to get pygeoapi running local on my Windows 10 laptop.
I've installed python 3.7.3 x64 into D:\python37 (I've already multiple python installations from Visual Studio 2017, ArcMap and Arcgis Pro and I think it's better to start with a fresh and latest version here)

set PATH=%PATH%;D:\python37\;D:\python37\Scripts
git clone https://github.com/geopython/pygeoapi.git
cd pygeoapi
pip install -r requirements.txt
pip install -r requirements-dev.txt
#install provider requirements accordingly from requirements-provider.txt
pip install -e .
#made a manual copy to local.config.yml in Explorer
#TODO: what is most important to edit?
SET PYGEOAPI_CONFIG=D:\pygeoapi\source\pygeoapi\local.config.yml
pygeoapi generate-openapi-document -c local.config.yml > openapi.yml 

after this line I get an exception:

Traceback (most recent call last):
  File "D:\python37\Scripts\pygeoapi-script.py", line 11, in <module>
    load_entry_point('pygeoapi', 'console_scripts', 'pygeoapi')()
  File "d:\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "d:\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "d:\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\python37\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "d:\pygeoapi\source\pygeoapi\pygeoapi\openapi.py", line 482, in generate_openapi_document
    click.echo(yaml.safe_dump(get_oas(s), default_flow_style=False))
  File "d:\pygeoapi\source\pygeoapi\pygeoapi\openapi.py", line 467, in get_oas
    return get_oas_30(cfg)
  File "d:\pygeoapi\source\pygeoapi\pygeoapi\openapi.py", line 208, in get_oas_30
    p = load_plugin('provider', cfg['datasets'][k]['provider'])
  File "d:\pygeoapi\source\pygeoapi\pygeoapi\plugin.py", line 88, in load_plugin
    module = importlib.import_module(packagename)
  File "d:\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\pygeoapi\source\pygeoapi\pygeoapi\provider\elasticsearch_.py", line 33, in <module>
    from elasticsearch import Elasticsearch, exceptions, helpers
ModuleNotFoundError: No module named 'elasticsearch'

**Comment by justb4** [comment]
Have you installed Provider requirements?

```
pip install -r requirements-provider.txt
````
This will get you probably in some other install issues.

Best is to start with a minimal ` local.config.yml`, only with `Observations` dataset. We are working on a minimal setup/config for exactly this setup problem. See issue #154.

**Comment by PeaceNlove** [comment]
After some research I made another fresh start with Anaconda and also followed your suggestion to run:
pip install -r requirements-provider.txt
So not sure what fixed it, but http://localhost:5000/ is working now :-)
Might be an idea to add information about what's required to start working with pygeoapi and the installation script should have this requirements provider line also.
