### ISSUE TITLE
Country item throws an error if format is HTML

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#205]
# How to reproduce

Start a container with:

`docker run -p 5000:80 -it geopython/pygeoapi run`

Request a single item:

`curl -XGET http://localhost:5000/collections/countries/items/9?f=html`

JSON format is working well though.

The traceback error is:

```
[2019-07-29T09:16:34Z] {/usr/local/lib/python3.7/dist-packages/flask/app.py:1891} ERROR - Exception on /collections/countries/items/9 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/pygeoapi/pygeoapi/flask_app.py", line 121, in dataset
    request.headers, request.args, feature_collection, feature)
  File "/pygeoapi/pygeoapi/api.py", line 72, in inner
    return func(cls, headers_, format_, *args, **kwargs)
  File "/pygeoapi/pygeoapi/api.py", line 675, in get_feature
    content)
  File "/pygeoapi/pygeoapi/api.py", line 862, in _render_j2_template
    return template.render(config=config, data=data, version=__version__)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/pygeoapi/pygeoapi/templates/item.html", line 12, in top-level template code
    {{ v | urlize() }}
  File "/pygeoapi/pygeoapi/templates/base.html", line 47, in top-level template code
    {% block body %}
  File "/pygeoapi/pygeoapi/templates/item.html", line 55, in block "body"
    {% for k, v in data['properties'].items() %}
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'properties'
```

**Comment by justb4** [comment]
Confirmed. This is the behaviour as in #95 (that is why I will re-open): HTML formatting (`Jinja2`) fails with the `sqlite` Provider since a `FeatureCollection` is returned (i.s.o. single Feature), see also http://localhost:5000/collections/countries/items/9?f=json (FeatureCollection) vs
e.g. http://localhost:5000/collections/obs/items/371?f=json (single `Feature`).

You can try to serve Countries sqlite dataset instead via the `OGRProvider`.

**Comment by francbartoli** [comment]
Thanks @justb4, I believe then we can consider this as a duplicate (because it is a consequence). I would close if you agree

**Comment by justb4** [comment]
Ok, duplicate yes.
