### ISSUE TITLE
Serving collections from an ES backend with geojson ingested by ogr2ogr fails

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#379]
Steps to reproduce the issue:

Load the data
--------------

```shell
docker run --rm --network=host -u $(id -u ${USER}):$(id -g ${USER}) \
-v $(pwd):/data \
-e OGR_GEOJSON_MAX_OBJ_SIZE=500MB \
osgeo/gdal:alpine-small-latest \
ogr2ogr -lco INDEX_NAME=places -lco NOT_ANALYZED_FIELDS={ALL} -lco FID=geonameid -lco OVERWRITE_INDEX=YES -overwrite ES:http://localhost:9200 /data/tests/data/ne_110m_populated_places_simple.geojson
```

pygeoapi config
----------------

```yaml
datasets:
    places:
        title: Places
        description: Populated places
        keywords:
            - places
            - geonames
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://www.example.org
              hreflang: en-EN
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: null
                end: now  # or empty
        provider:
            name: Elasticsearch
            data: http://localhost:9200/places
            id_field: geonameid
```

Request
--------

`curl -XGET http://localhost/collections/places/items?f=json`

Error
-----

```python
Traceback (most recent call last):
  File "/Users/geobart/.pyenv/versions/3.7.6/envs/pygeoapi/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/geobart/.pyenv/versions/3.7.6/envs/pygeoapi/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/geobart/.pyenv/versions/3.7.6/envs/pygeoapi/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/geobart/.pyenv/versions/3.7.6/envs/pygeoapi/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/geobart/.pyenv/versions/3.7.6/envs/pygeoapi/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/geobart/.pyenv/versions/3.7.6/envs/pygeoapi/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/geobart/.pyenv/versions/3.7.6/envs/pygeoapi/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/geobart/.pyenv/versions/3.7.6/envs/pygeoapi/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/geobart/.pyenv/versions/3.7.6/envs/pygeoapi/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/geobart/.pyenv/versions/3.7.6/envs/pygeoapi/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/geobart/code/Fao/WaterProductivity/pygeoapi/pygeoapi/flask_app.py", line 177, in dataset
    request.headers, request.args, feature_collection)
  File "/Users/geobart/code/Fao/WaterProductivity/pygeoapi/pygeoapi/api.py", line 625, in get_collection_items
    self.config['datasets'][dataset]['provider'])
  File "/Users/geobart/code/Fao/WaterProductivity/pygeoapi/pygeoapi/plugin.py", line 93, in load_plugin
    plugin = class_(plugin_def)
  File "/Users/geobart/code/Fao/WaterProductivity/pygeoapi/pygeoapi/provider/elasticsearch_.py", line 73, in __init__
    self.fields = self.get_fields()
  File "/Users/geobart/code/Fao/WaterProductivity/pygeoapi/pygeoapi/provider/elasticsearch_.py", line 88, in get_fields
    p = ii[self.index_name]['mappings']['properties']['properties']  # noqa
KeyError: 'properties'
```

**Comment by tomkralidis** [comment]
@francbartoli I'm having trouble to reproduce:

```bash
(pygeoapi) (base) tomkralidis@aruba:~/Dev/pygeoapi/pygeoapi$ 
docker run --rm --network=host -u $(id -u ${USER}):$(id -g ${USER}) \
-v $(pwd):/data \
-e OGR_GEOJSON_MAX_OBJ_SIZE=500MB \
osgeo/gdal:alpine-small-latest \
ogr2ogr -lco INDEX_NAME=places -lco NOT_ANALYZED_FIELDS={ALL} -lco FID=geonameid -lco OVERWRITE=YES ES:http://localhost:9200 /data/tests/data/ne_110m_populated_places_simple.geojson
ERROR 1: Failed to connect to localhost port 9200: Connection refused
ERROR 1: Unable to open existing output datasource 'ES:http://localhost:9200'.

(pygeoapi) (base) tomkralidis@aruba:~/Dev/pygeoapi/pygeoapi$ ogr2ogr -lco INDEX_NAME=places -lco NOT_ANALYZED_FIELDS={ALL} -lco FID=geonameid -lco OVERWRITE=YES ES:http://localhost:9200 ./tests/data/ne_110m_populated_places_simple.geojson
ERROR 1: HTTP error code : 400
ERROR 1: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."},"status":400}
ERROR 1: Unable to write feature 0 from layer ne_110m_populated_places_simple.
ERROR 1: Terminating translation prematurely after failed
translation of layer ne_110m_populated_places_simple (use -skipfailures to skip errors)
```

**Comment by francbartoli** [comment]
@tomkralidis please see my updated command above. Also, I realized it is not creating a Feature object within ES like our pygeoapi script. I'm facing with these output:

```json
{
    "took": 1,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 243,
            "relation": "eq"
        },
        "max_score": 1.0,
        "hits": [
            {
                "_index": "places",
                "_type": "_doc",
                "_id": "hvzt03AB8v4-ZVfF0qjW",
                "_score": 1.0,
                "_source": {
                    "geonameid": 6691831.0,
                    "geometry": {
                        "type": "POINT",
                        "coordinates": [
                            12.453386545,
                            41.90328218
                        ]
                    },
                    "scalerank": 8,
                    "natscale": 10,
                    "labelrank": 3,
                    "featurecla": "Admin-0 capital",
                    "name": "Vatican City",
                    "namepar": null,
                    "namealt": null,
                    "diffascii": 0,
                    "nameascii": "Vatican City",
                    "adm0cap": 1.0,
                    "capalt": null,
                    "capin": null,
                    "worldcity": 1.0,
                    "megacity": 0,
                    "sov0name": "Vatican (Holy Sea)",
                    "sov_a3": "VAT",
                    "adm0name": "Vatican (Holy See)",
                    "adm0_a3": "VAT",
                    "adm1name": "Lazio",
                    "iso_a2": "VA",
                    "note": null,
                    "latitude": 41.900012226400001,
                    "longitude": 12.4478083889,
                    "changed": 4.0,
                    "namediff": 0,
                    "diffnote": "Changed scale rank.",
                    "pop_max": 832,
                    "pop_min": 832,
                    "pop_other": 562430,
                    "rank_max": 2,
                    "rank_min": 2,
                    "meganame": null,
                    "ls_name": "Vatican City",
                    "ls_match": 1,
                    "checkme": 0,
                    "min_zoom": 7.0
                }
            },
...
}
```

Maybe a GDAL bug in writing the index?

**Comment by tomkralidis** [comment]
Thanks @francbartoli the below seems to have to worked (see the ES URL):
```shell
(base) (pygeoapi) tomkralidis@aruba:~/Dev/pygeoapi/pygeoapi$ docker run   --rm -u $(id -u ${USER}):$(id -g ${USER}) -v $(pwd):/data -e OGR_GEOJSON_MAX_OBJ_SIZE=500MB osgeo/gdal:alpine-small-latest ogr2ogr -lco INDEX_NAME=places -lco NOT_ANALYZED_FIELDS={ALL} -lco FID=geonameid -lco OVERWRITE_INDEX=YES -overwrite ES:http://host.docker.internal:9200 /data/tests/data/ne_110m_populated_places_simple.geojson
```

**Comment by tomkralidis** [comment]
Update: I'm able to reproduce.  To summarize, the current pygeoapi ES provider is based on an index of GeoJSON formatted documents, whereas GDAL 3.1+ will write ES indexes with flat, simple features-ish documents.  Options:

1. update current pygeoapi ES provider to handle both the abovementioned cases
2. guide users and documentation to use the OGR provider for GDAL-generated ES indexes
3. create an `ElasticsearchGDAL` provider for the GDAL use case (to cut down on `if/else`-ing in option 1)
4. other options?

**Comment by francbartoli** [comment]
Thanks @tomkralidis, I'm inclined to not create a specific provider for the GDAL use case, even because this would mean to distinguish the ES version 7 and above.
I'd rather we go with the option 1 to have long term support for the different ES versions.
Currently, the most relevant block to accomplish this is:

```json
...
{
                "_index": "places",
                "_type": "_doc",
                "_id": "hvzt03AB8v4-ZVfF0qjW",
                "_score": 1.0,
                "_source": {
                    "geonameid": 6691831.0,
...
```

while I'd like to force the `_id` field, during the ingestion, to have the value from `geonameid ` (help appreciated)

```json
...
{
                "_index": "places",
                "_type": "_doc",
                "_id": "6691831",
                "_score": 1.0,
                "_source": {
                    "geonameid": 6691831.0,
...
```

Once I'll get that then it will be quite easy to handle both cases.

**Comment by tomkralidis** [comment]
Thanks @francbartoli .  IMHO the id persistence is a GDAL issue vs. pygeoapi requirement.  Having said this, #380 includes support for both fetching by id or query by the id field, but the former is a cleaner approach.
