### ISSUE TITLE
Elasticsearch provider not loading index

### ISSUE THREAD

**Issue by jvanulde** [geopython/pygeoapi#505]
**Description**
I am using the sample dataset `ne_110m_lakes.geojson` to troubleshoot a connection that I have with another index. However, I can't get it to connect.

**Steps to Reproduce**

1. Create the index in local Elasticsearch:
    `$ python load_es_data.py data/ne_110m_lakes.geojson name`

_Note: I tried with id field but the script failed. Name is unique so I tried that and it worked._

2. add configuration to example-config.yml:
    
```
    lakes:
        type: collection
        title: Lakes
        description: Some cool lakes
        keywords:
            - waterbody
        links:
            - type: text/html
              rel: canonical
              title: information
              href: http://www.cheese.com/
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2020-08-06
                end: null  # or empty (either means open ended)
        provider:
           - type: feature
              name: Elasticsearch
              data: http://localhost:9200/ne_110m_lakes
              id_field: name
```

3. export configuration and generate openapi document:
    `$ export PYGEOAPI_CONFIG=example-config.yml`
    `$ pygeoapi generate-openapi-document -c $PYGEOAPI_CONFIG > $PYGEOAPI_OPENAPI`

**Expected behavior**
An openapi document gets generated.

**Screenshots/Tracebacks**
Here is the stack trace:

```
Traceback (most recent call last):
  File "/Users/nrcan/Sites/foobar-pygeoapi/pygeoapi/bin/pygeoapi", line 11, in <module>
    load_entry_point('pygeoapi==0.9.dev0', 'console_scripts', 'pygeoapi')()
  File "/Users/nrcan/Sites/foobar-pygeoapi/pygeoapi/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nrcan/Sites/foobar-pygeoapi/pygeoapi/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/nrcan/Sites/foobar-pygeoapi/pygeoapi/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nrcan/Sites/foobar-pygeoapi/pygeoapi/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nrcan/Sites/foobar-pygeoapi/pygeoapi/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/nrcan/Sites/foobar-pygeoapi/pygeoapi/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/nrcan/Sites/foobar-pygeoapi/pygeoapi/lib/python3.7/site-packages/pygeoapi-0.9.dev0-py3.7.egg/pygeoapi/openapi.py", line 649, in generate_openapi_document
    click.echo(yaml.safe_dump(get_oas(s), default_flow_style=False))
  File "/Users/nrcan/Sites/foobar-pygeoapi/pygeoapi/lib/python3.7/site-packages/pygeoapi-0.9.dev0-py3.7.egg/pygeoapi/openapi.py", line 634, in get_oas
    return get_oas_30(cfg)
  File "/Users/nrcan/Sites/foobar-pygeoapi/pygeoapi/lib/python3.7/site-packages/pygeoapi-0.9.dev0-py3.7.egg/pygeoapi/openapi.py", line 412, in get_oas_30
    collections[k]['providers'], 'feature'))
KeyError: 'providers'
```

Here is the index at http://localhost:9200/ne_110m_lakes:

```
{
  "ne_110m_lakes": {
    "aliases": {},
    "mappings": {
      "properties": {
        "geometry": {
          "type": "geo_shape"
        },
        "id": {
          "type": "long"
        },
        "properties": {
          "properties": {
            "admin": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "featureclass": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "name": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "name_alt": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "nameascii": {
              "type": "text",
              "fields": {
                "raw": {
                  "type": "keyword"
                }
              }
            },
            "scalerank": {
              "type": "long"
            },
            "trr": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            }
          }
        },
        "type": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        }
      }
    },
    "settings": {
      "index": {
        "creation_date": "1596751486517",
        "number_of_shards": "1",
        "number_of_replicas": "0",
        "uuid": "EEpxV5ZUSjKugMbSpYVaTA",
        "version": {
          "created": "7070199"
        },
        "provided_name": "ne_110m_lakes"
      }
    }
  }
}
```

Here is a truncated feature from the index:

   ```
 {
        "_index": "ne_110m_lakes",
        "_type": "_doc",
        "_id": "Lake Baikal",
        "_score": 1,
        "_source": {
          "geometry": {
            "coordinates": [
              [
                [
                  106.57998579307912,
                  52.79998159444554
                ],
                ...
            ],
            "type": "Polygon"
          },
          "id": 0,
          "properties": {
            "admin": null,
            "featureclass": "Lake",
            "name": "Lake Baikal",
            "name_alt": "https://en.wikipedia.org/wiki/Lake_Baikal",
            "scalerank": 0
          },
          "type": "Feature"
        }
      }

```
**Environment**
 - OS: MacOS
 - Python version: 3.7.3
 - pygeoapi version: latest

**Comment by tomkralidis** [comment]
@jvanulde can you update your configuration? Your provider block should now be:
```yaml
providers:
 - type: feature
   name: Elasticsearch
   data: http://localhost:9200/ne_110m_lakes
   id_field: name
```

**Comment by jvanulde** [comment]
> @jvanulde can you update your configuration? Your provider block should now be:
> 
> ```yaml
> providers:
>  - type: feature
>    name: Elasticsearch
>    data: http://localhost:9200/ne_110m_lakes
>    id_field: name
> ```

Updated. Same error. Is there a way to test to see if the provider (i.e. Elasticsearch) is installed?

**Comment by jvanulde** [comment]
The issue was indentation in the configuration file. Problem resolved.
