### ISSUE TITLE
WFS example in docs doesn't work

### ISSUE THREAD

**Issue by KoalaGeo** [geopython/pygeoapi#648]
**Description**
pygeoapi will not run if using the example WFS config in the documentation 

**Steps to Reproduce**

https://github.com/BritishGeologicalSurvey/bgs-pygeoapi/blob/inspire/content/local.config.yml#L295 
Docker build & run - https://github.com/BritishGeologicalSurvey/bgs-pygeoapi/blob/inspire/Dockerfile 

**Expected behavior**
Run pygeoapi and access WFS

**Screenshots/Tracebacks**
```
edd@pop-os:~/Documents/pygeoapi$ docker run -p 80:80 pygeoapi
START /entrypoint.sh
Trying to generate openapi.yml
Traceback (most recent call last):
  File "/usr/local/bin/pygeoapi", line 11, in <module>
    load_entry_point('pygeoapi', 'console_scripts', 'pygeoapi')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/pygeoapi/pygeoapi/openapi.py", line 947, in generate_openapi_document
    s = yaml_load(ff)
  File "/pygeoapi/pygeoapi/util.py", line 130, in yaml_load
    return yaml.load(fh, Loader=EnvVarLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 392, in parse_block_sequence_entry
    raise ParserError("while parsing a block collection", self.marks[-1],
yaml.parser.ParserError: while parsing a block collection
  in "/pygeoapi/local.config.yml", line 296, column 13
expected <block end>, but found '?'
  in "/pygeoapi/local.config.yml", line 297, column 13
ERROR: openapi.yml could not be generated ERROR
```

**Environment**
Docker using latest

**Comment by nmtoken** [comment]
Example service is available and ogrinfo gives a response:

    ogrinfo -so -al "WFS:https://geodata.nationaalgeoregister.nl/rdinfo/wfs?" "rdinfo:stations"

Gives:

    INFO: Open of `WFS:https://geodata.nationaalgeoregister.nl/rdinfo/wfs?'
          using driver `WFS' successful.
    Metadata:
      ABSTRACT=Overzicht van de ligging van de RD-punten, GNSS-referentiestations en GNSS-kernnetpunten in Nederland met de bijbehorende omschrijvingen en coordinaten in het stelsel van de Rijksdriehoeksmeting (RD) en het Europese stelsel ETRS-89. Op http://www.kadaster.nl/web/artikel/download/Beschrijving-velden-RDinfo-PDOK-1.htm is uitleg beschikbaar over de inhoud van de velden van deze dataset.
      PROVIDER_NAME=PDOK
      TITLE=RD-punten WFS

    Layer name: rdinfo:stations
    Metadata:
      ABSTRACT=Overzicht van de ligging van de RD-punten, GNSS-referentiestations en GNSS-kernnetpunten in Nederland met de bijbehorende omschrijvingen en coordinaten in het stelsel van de Rijksdriehoeksmeting (RD) en het Europese stelsel ETRS-89. Op http://www.kadaster.nl/web/artikel/download/Beschrijving-velden-RDinfo-PDOK-1.htm is uitleg beschikbaar over de inhoud van de velden van deze dataset.
      KEYWORD_1=stations infoMapAccessService
      TITLE=stations
    Geometry: Unknown (any)
    Feature Count: 12613
    Extent: (-41259.100000, 0.000000) - (299233.700000, 623285.770000)
    Layer SRS WKT:
    PROJCRS["Amersfoort / RD New",
        BASEGEOGCRS["Amersfoort",
            DATUM["Amersfoort",
                ELLIPSOID["Bessel 1841",6377397.155,299.1528128,
                    LENGTHUNIT["metre",1]]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433]],
            ID["EPSG",4289]],
        CONVERSION["RD New",
            METHOD["Oblique Stereographic",
                ID["EPSG",9809]],
            PARAMETER["Latitude of natural origin",52.1561605555556,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8801]],
            PARAMETER["Longitude of natural origin",5.38763888888889,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8802]],
            PARAMETER["Scale factor at natural origin",0.9999079,
                SCALEUNIT["unity",1],
                ID["EPSG",8805]],
            PARAMETER["False easting",155000,
                LENGTHUNIT["metre",1],
                ID["EPSG",8806]],
            PARAMETER["False northing",463000,
                LENGTHUNIT["metre",1],
                ID["EPSG",8807]]],
        CS[Cartesian,2],
            AXIS["easting (X)",east,
                ORDER[1],
                LENGTHUNIT["metre",1]],
            AXIS["northing (Y)",north,
                ORDER[2],
                LENGTHUNIT["metre",1]],
        USAGE[
            SCOPE["unknown"],
            AREA["Netherlands - onshore"],
            BBOX[50.75,3.2,53.7,7.22]],
        ID["EPSG",28992]]
    Data axis to CRS axis mapping: 1,2
    Geometry Column = geom
    gml_id: String (0.0) NOT NULL
    msFID: String (0.0)
    gid: String (0.0)
    blad: String (0.0)
    punt: String (0.0)
    jaar: String (0.0)
    maand: String (0.0)
    dag: String (0.0)
    station: String (0.0)
    omschrext: String (0.0)
    omschrint: String (0.0)
    xrd: String (0.0)
    yrd: String (0.0)
    phi: String (0.0)
    lambda: String (0.0)
    h: String (0.0)
    gps: String (0.0)
    peilmerk: String (0.0)

**Comment by KoalaGeo** [comment]
Issue was with incorrect indentation of my config file, issue closed.
