### ISSUE TITLE
ES provider defaulting to HTTP GET on HTTPS resource

### ISSUE THREAD

**Issue by jvanulde** [geopython/pygeoapi#653]
I have the following configuration:

     providers:
            - type: feature
              name: Elasticsearch
              data: https://my.somedomain.com:443/my_index
              id_field: AssetID

The request fails with the following stack trace:

    Cannot connect to Elasticsearch
    Traceback (most recent call last):
      File "/usr/local/bin/pygeoapi", line 11, in <module>
        load_entry_point('pygeoapi', 'console_scripts', 'pygeoapi')()
      File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 21, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/pygeoapi/pygeoapi/openapi.py", line 846, in generate_openapi_document
        click.echo(yaml.safe_dump(get_oas(s), default_flow_style=False))
      File "/pygeoapi/pygeoapi/openapi.py", line 831, in get_oas
        return get_oas_30(cfg)
      File "/pygeoapi/pygeoapi/openapi.py", line 395, in get_oas_30
        p = load_plugin('provider', get_provider_by_type(
      File "/pygeoapi/pygeoapi/plugin.py", line 97, in load_plugin
        plugin = class_(plugin_def)
      File "/pygeoapi/pygeoapi/provider/elasticsearch_.py", line 73, in __init__
        raise ProviderConnectionError(msg)
    pygeoapi.provider.base.ProviderConnectionError: Cannot connect to Elasticsearch
    ERROR: openapi.yml could not be generated ERROR

See: https://github.com/geopython/pygeoapi/blob/22a46ec5c8365d8c0d290a8776edae8d94276010/pygeoapi/provider/elasticsearch_.py#L61

**Comment by tomkralidis** [comment]
Fixed in #654
