### ISSUE TITLE
[postgresql] no support for non-default schema behind pgbouncer

### ISSUE THREAD

**Issue by landryb** [geopython/pygeoapi#682]
experimenting with pygeoapi 0.10.1, ive tried setting it up against a postgis database which is behind pgbouncer.

my postgis tables are not in the default `public` schema, so i've tried using 
```
search_path: [bdtopov3_202103_aura, public]
table: commune
```
this fails pretty badly when generating the openapi document:
```
Couldn't connect to Postgis using:{'host': 'xxx', 'dbname': 'gisdata', 'user': 'xxx', 'password': 'xxx', 'options': '-c                 search_path=bdtopov3_202103_aura,public'}
Traceback (most recent call last):
  File "/srv/pygeoapi/venv/lib/python3.7/site-packages/pygeoapi/provider/postgresql.py", line 103, in __enter__
    self.conn = psycopg2.connect(**self.conn_dic)
  File "/srv/pygeoapi/venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: ERROR:  unsupported startup parameter: options
```
i figured out it was a pgbouncer issue (it doesnt support arbitrary options as done in https://github.com/geopython/pygeoapi/blob/master/pygeoapi/provider/postgresql.py#L99, as found out by other projects, https://github.com/psycopg/psycopg2/issues/1118 as an example), so tried putting the schema name in the table name:
```
table: bdtopov3_202103_aura.commune
```
alas, this blows differently:
```
[2021-04-30T13:54:10Z] {/srv/pygeoapi/venv/lib/python3.7/site-packages/pygeoapi/provider/postgresql.py:278} ERROR - Error executing sql_query: DECLARE "geo_cursor" CURSOR FOR  SELECT DISTINCT ,ST_AsGeoJSON("geometrie") FROM "bdtopov3_202103_aura.commune"
```
my analysis is that `db.columns` is None, as the psql provider tries to fetch column names using another sql query in the `information_schema` schema, but there's a hard match against `table_name` here https://github.com/geopython/pygeoapi/blob/master/pygeoapi/provider/postgresql.py#L114 so no columns are found.

an option here would be to strip what's before a dot in `self.table_name` so that the right table is found, but then one would also need to check the schema when looking for columns.

another option would be to have a pgbouncer-compatible way of setting the schema, usually one does something along the lines of 
```
cur.execute("SELECT pg_catalog.set_config('search_path', %(schema)s, false)", {'schema': self.schema})
```
but that's on the cursor, not the db connection object.

trying this small patch:
```
--- /srv/pygeoapi/venv/lib/python3.7/site-packages/pygeoapi/provider/postgresql.py.orig 2021-04-30 14:17:44.884989802 +0200
+++ /srv/pygeoapi/venv/lib/python3.7/site-packages/pygeoapi/provider/postgresql.py      2021-04-30 14:38:54.542683230 +0200
@@ -96,10 +96,6 @@
     def __enter__(self):
         try:
             search_path = self.conn_dic.pop('search_path', ['public'])
-            if search_path != ['public']:
-                self.conn_dic["options"] = '-c \
-                search_path={}'.format(",".join(search_path))
-                LOGGER.debug('Using search path: {} '.format(search_path))
             self.conn = psycopg2.connect(**self.conn_dic)
             self.conn.set_client_encoding('utf8')
 
@@ -109,6 +105,9 @@
             raise ProviderConnectionError()
 
         self.cur = self.conn.cursor()
+        if search_path != ['public']:
+            self.cur.execute("SELECT pg_catalog.set_config('search_path', '{}', false)".format(",".join(search_path)))
+            LOGGER.debug('Using search path: {} '.format(search_path))
         if self.context == 'query':
             # Getting columns
             query_cols = "SELECT column_name, udt_name FROM information_schema.columns \
```
allows me to generate the openapi doc with a table not in the default scheme (eg the provider manages to list columns), but that's not enough for runtime to be okay (as runtime uses a different/distinct db cnx).

I'll dig into that a bit more. maybe i just need to set the `search_path` on each cursor used.

**Comment by landryb** [comment]
adding a bit more code, i have something that sort of works at the first sql query, but not afterwards, so i feel that the `pop()` thats done in https://github.com/geopython/pygeoapi/blob/master/pygeoapi/provider/postgresql.py#L98 somewhat 'loses' the search path information for subsequent queries.

**Comment by landryb** [comment]
from what i can tell from the debug logs, the `pop` definitely loses something. doing a single hit on the API, the `PostgreSQLProvider` class seems instanciated two times (why ??), and the second instance has 'lost' the search path:
```
[2021-04-30T15:39:34Z] {/srv/pygeoapi/venv/lib/python3.7/site-packages/pygeoapi/provider/postgresql.py:166} DEBUG - Search path:['bdtopov3_202103_aura', 'public']
[2021-04-30T15:39:34Z] {/srv/pygeoapi/venv/lib/python3.7/site-packages/pygeoapi/provider/postgresql.py:168} DEBUG - Get available fields/properties
[2021-04-30T15:39:34Z] {/srv/pygeoapi/venv/lib/python3.7/site-packages/pygeoapi/api.py:1125} DEBUG - Fetching id COMMUNE_0000000009747951
[2021-04-30T15:39:35Z] {/srv/pygeoapi/venv/lib/python3.7/site-packages/pygeoapi/provider/postgresql.py:166} DEBUG - Search path:['public']
[2021-04-30T15:39:35Z] {/srv/pygeoapi/venv/lib/python3.7/site-packages/pygeoapi/provider/postgresql.py:168} DEBUG - Get available fields/properties
[2021-04-30T15:39:35Z] {/srv/pygeoapi/venv/lib/python3.7/site-packages/pygeoapi/api.py:1125} DEBUG - Fetching id COMMUNE_0000000009747951
```
so the second query fails to find the sql table in the default schema.

**Comment by landryb** [comment]
so far the workaround i've found was to assign a copy of the data dict in the constructor to avoid losing the information:
```
-        self.conn_dic = provider_def['data']
+        self.conn_dic = provider_def['data'].copy()
```
but there might of course be a cleaner solution.

is a PR welcome with all my various hacks/changes to properly support setting the database search path ?
