### ISSUE TITLE
"Install in 5 minutes" instructions are broken

### ISSUE THREAD

**Issue by l0b0** [geopython/pygeoapi#686]
**Description**

Following the ["Install in 5 minutes" instructions](https://pygeoapi.io/) instructions literally doesn't result in a working installation. There's a missing dependency, and after installing that I still get a `ProviderConnectionError`.

**Steps to Reproduce**

1. `cd` into a directory which doesn't already contain a "pygeoapi" directory
1. Run the commands in the instructions:
   ```
   python3 -m venv pygeoapi
   cd pygeoapi
   . bin/activate
   git clone https://github.com/geopython/pygeoapi.git
   cd pygeoapi
   pip3 install -r requirements.txt
   python setup.py install
   cp pygeoapi-config.yml example-config.yml
   export PYGEOAPI_CONFIG=example-config.yml
   export PYGEOAPI_OPENAPI=example-openapi.yml
   pygeoapi generate-openapi-document -c $PYGEOAPI_CONFIG > $PYGEOAPI_OPENAPI
   ```

**Expected behavior**

This should generate a non-empty example-openapi.yml file without errors.

**Actual behavior**

```console
$ pygeoapi generate-openapi-document -c $PYGEOAPI_CONFIG > $PYGEOAPI_OPENAPI
Traceback (most recent call last):
  File "/home/victor/dev/pygeoapi/bin/pygeoapi", line 33, in <module>
    sys.exit(load_entry_point('pygeoapi==0.11.dev0', 'console_scripts', 'pygeoapi')())
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/openapi.py", line 1003, in generate_openapi_document
    click.echo(yaml.safe_dump(get_oas(s), default_flow_style=False))
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/openapi.py", line 984, in get_oas
    return get_oas_30(cfg)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/openapi.py", line 735, in get_oas_30
    ep = load_plugin('provider', edr_extension)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/plugin.py", line 102, in load_plugin
    module = importlib.import_module(packagename)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/provider/xarray_edr.py", line 33, in <module>
    from pygeoapi.provider.xarray_ import _to_datetime_string, XarrayProvider
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/provider/xarray_.py", line 35, in <module>
    import xarray
ModuleNotFoundError: No module named 'xarray'
```

Installing xarray is not enough to fix it either:

```
$ pip install xarray
[…]
$ pygeoapi generate-openapi-document -c $PYGEOAPI_CONFIG > $PYGEOAPI_OPENAPI
cannot guess the engine, try passing one explicitly
Traceback (most recent call last):
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/provider/xarray_.py", line 64, in __init__
    self._data = open_func(self.data)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/xarray/backends/api.py", line 485, in open_dataset
    engine = plugins.guess_engine(filename_or_obj)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/xarray/backends/plugins.py", line 112, in guess_engine
    raise ValueError("cannot guess the engine, try passing one explicitly")
ValueError: cannot guess the engine, try passing one explicitly

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/victor/dev/pygeoapi/bin/pygeoapi", line 33, in <module>
    sys.exit(load_entry_point('pygeoapi==0.11.dev0', 'console_scripts', 'pygeoapi')())
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/openapi.py", line 1003, in generate_openapi_document
    click.echo(yaml.safe_dump(get_oas(s), default_flow_style=False))
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/openapi.py", line 984, in get_oas
    return get_oas_30(cfg)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/openapi.py", line 735, in get_oas_30
    ep = load_plugin('provider', edr_extension)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/plugin.py", line 104, in load_plugin
    plugin = class_(plugin_def)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/provider/xarray_edr.py", line 50, in __init__
    XarrayProvider.__init__(self, provider_def)
  File "/home/victor/dev/pygeoapi/lib/python3.9/site-packages/pygeoapi-0.11.dev0-py3.9.egg/pygeoapi/provider/xarray_.py", line 75, in __init__
    raise ProviderConnectionError(err)
pygeoapi.provider.base.ProviderConnectionError: cannot guess the engine, try passing one explicitly
```

**Environment**
 - OS: Arch Linux
 - Python version: 3.9.4
 - pygeoapi version: commit a4bf35d310f66aa03889e086de4a0d3d4090f394

**Comment by jmbelanger** [comment]
Hi,
   Just to let you know it worked for me after getting rid of icoads-sst  ressource in the config and 
 installing xarray + tinydb.

Cheers,
Jean-Marc

**Comment by l0b0** [comment]
@tomkralidis Sorry for the late feedback. This time (commit a4bf35d310f66aa03889e086de4a0d3d4090f394) `python setup.py install` resulted in

> error: click 8.0.0 is installed but click<8,>=4.0 is required by {'rasterio'}

**Comment by tomkralidis** [comment]
Thanks for the feedback @jmbelanger and @l0b0.  @l0b0 can you update `requirements.txt` with:

`click<8`

And try again?  That should pin click down given the rasterio requirement.

We can update master once validated.

**Comment by l0b0** [comment]
```console
$ pygeoapi generate-openapi-document -c $PYGEOAPI_CONFIG > $PYGEOAPI_OPENAPI
ModuleNotFoundError: No module named 'tinydb'
```

**Comment by tomkralidis** [comment]
Can you add `tinydb` in `requirements.txt` and try again?  We have tinydb in `requirements-manager.txt`, which is not part of the default install, but seeing that it now backs processing management and OGC API - Records, will add it to core requirements.

**Comment by metmikel** [comment]
I've also been evaluating pygeoapi for a project we're working on and have seen this same issue.  I can confirm that after installing `xarray` and `tinydb` and commenting out the collection in my config that was using the xarray provider (to read a NetCDF file) fixed the error `pygeoapi.provider.base.ProviderConnectionError: cannot guess the engine, try passing one explicitly`

**Comment by tomkralidis** [comment]
Thanks for the reports/feedback. A PR (#691) branch can be found at https://github.com/geopython/pygeoapi/tree/issue-686 with proposed changes/updates (note: you shouldn't need to install xarray).

**Comment by tomkralidis** [comment]
#691 pushed to master branch.  If folks can test/validate, that would be great.

**Comment by metmikel** [comment]
Yep, I pulled this change, recreated my virtual environment and ran the other steps in the five minute install instructions successfully so it looks good.
