### ISSUE TITLE
cannot use OpenAPI JSON document for PYGEOAPI_OPENAPI

### ISSUE THREAD

**Issue by StephenWithPH** [geopython/pygeoapi#775]
**Description**
Having generated an OpenAPI document as JSON per [the docs](https://docs.pygeoapi.io/en/latest/administration.html#creating-the-openapi-document)...
```sh
pygeoapi openapi generate /path/to/my-pygeoapi-config.yml -f json > /path/to/my-pygeoapi-openapi.json
```

... and provided it to `pygeoapi`...
```sh
export PYGEOAPI_CONFIG=/path/to/my-pygeoapi-config.yml
export PYGEOAPI_OPENAPI=/path/to/my-pygeoapi-openapi.json
pygeoapi serve
```

... the swagger page is broken...

![image](https://user-images.githubusercontent.com/2990492/132749116-238fc8c0-85a6-4565-985f-ed7b478787cf.png)

... and the link to download the raw OpenAPI document `500`s with:

```txt
Traceback (most recent call last):
  File "/Users//Library/Caches/pypoetry/virtualenvs/pygeoapi-AJYQC2VG-py3.8/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users//Library/Caches/pypoetry/virtualenvs/pygeoapi-AJYQC2VG-py3.8/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/Users//Library/Caches/pypoetry/virtualenvs/pygeoapi-AJYQC2VG-py3.8/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users//Library/Caches/pypoetry/virtualenvs/pygeoapi-AJYQC2VG-py3.8/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users//Library/Caches/pypoetry/virtualenvs/pygeoapi-AJYQC2VG-py3.8/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users//Library/Caches/pypoetry/virtualenvs/pygeoapi-AJYQC2VG-py3.8/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users//src/github.com/geopython/pygeoapi/pygeoapi/flask_app.py", line 140, in openapi
    return get_response(api_.openapi(request, openapi_))
  File "/Users//src/github.com/geopython/pygeoapi/pygeoapi/api.py", line 140, in inner
    return func(cls, req_out, *args[2:])
  File "/Users//src/github.com/geopython/pygeoapi/pygeoapi/api.py", line 693, in openapi
    return headers, 200, openapi.read()
ValueError: I/O operation on closed file.
```

Providing an OpenAPI document as yaml works just fine.

**Steps to Reproduce**
See above.

**Expected behavior**
I expect the Swagger page and raw OpenAPI download to work regardless of yaml or json.

**Screenshots/Tracebacks**
See above.

**Environment**
 - OS: MacOS
 - Python version: Python 3.8.11
 - pygeoapi version: `master` `774ff49f0060858fe3bec4d3ea73a970906baa6e`

**Comment by tomkralidis** [comment]
@StephenWithPH thanks for the report.  Can you test against latest master and report back?

**Comment by StephenWithPH** [comment]
@tomkralidis 🎉 

It works with json now. Thank you for the quick fix.

**Comment by tomkralidis** [comment]
Thanks for the clear and concise report/issue @StephenWithPH !
